trigger:
  name: pipelines-harness-exemplo-basico-trigger
  identifier: pipelinesharnessexemplobasicotrigger
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  stagesToExecute: []
  projectIdentifier: default_project
  pipelineIdentifier: pipelinesharnessexemplobasico
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: Toolbox_Playground
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          repoName: pipelines-harness-exemplo-basico
          actions: []
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - pipelinesharnessexemplobasicoinputset2