pipeline:
  name: toolbox-playground-harness
  identifier: toolboxplaygroundharness
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Toolbox_Playground
        repoName: harness
        build: <+input>
  stages:
    - stage:
        name: NodeJS
        identifier: NodeJS
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm install
                  description: instal npm packages
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm install
                      npm test
                  description: Test nodejs app
              - step:
                  name: Build
                  type: Run
                  spec:
                    command: |
                      docker build -t toolboxplayground/pipelines-exemplo-basico-desafio:latest .
              - step:
                  name: Push
                  type: Run
                  spec:
                    command: |
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                      docker push toolboxplayground/pipelines-exemplo-basico-desafio:latest
                  envVariables:
                    - name: DOCKER_USERNAME
                      value: <+secrets.getValue("docker_username_marcelobuzzetti")>
                    - name: DOCKER_PASSWORD
                      value: <+secrets.getValue("docker_password_marcelobuzzetti")>
