pipeline:
  name: toolbox-playground-harness
  identifier: toolboxplaygroundharness
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Toolbox_Playground
        repoName: harness
        build: <+input>
  stages:
    - stage:
        name: NodeJS
        identifier: NodeJS
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm install
                  description: instal npm packages
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm install
                      npm test
                  description: Test nodejs app
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Push Docker Image
                  identifier: Push_Docker_Image
                  spec:
                    connectorRef: Docker_Toolbox
                    repo: marcelobuzzettitoolbox/pipelines-exemplo-basico-desafio
                    tags:
                      - latest
